combat-duration: 5  # Thời gian combat tính bằng giây
blocked-commands: # Chặn xử dụng lệnh.
  - home
  - spawn
  - tpa
  - tpaccept
quit-commands:
  - kick %player% Bạn đã thoát game khi đang trong trạng thái combat!
  - say %player% đã bị xử lý vì thoát game khi đang trong combat!